export const graysCourseRecords = [
    {
        "osmType":  "way",
        "osmId":  149715001,
        "name":  "Thorpe Hall Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.534475,
        "lng":  0.750651,
        "distanceMiles":  18.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  160284665,
        "name":  "Three Rivers Golf \u0026 Country Club",
        "town":  "Cold Norton",
        "postcode":  "CM3 6RR",
        "holesTag":  "36_hole",
        "holesCount":  36,
        "par":  "72 + 64",
        "lat":  51.665758,
        "lng":  0.660874,
        "distanceMiles":  19.5,
        "website":  "https://www.threeriversclub.com/",
        "phone":  "+44 1621 829781;+44 1621 828631"
    },
    {
        "osmType":  "way",
        "osmId":  179150268,
        "name":  "West Park Pitch \u0026 Putt",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.735735,
        "lng":  0.454384,
        "distanceMiles":  18.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  147290433,
        "name":  "Toot Hill Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.693136,
        "lng":  0.190366,
        "distanceMiles":  16.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  112044082,
        "name":  "Allhallows Holiday Park Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.474826,
        "lng":  0.636595,
        "distanceMiles":  13.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  127582078,
        "name":  "Warley Park Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.589142,
        "lng":  0.306313,
        "distanceMiles":  7.9,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  128679377,
        "name":  "Thorndon Park Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.595948,
        "lng":  0.34113,
        "distanceMiles":  8.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  231182207,
        "name":  "Hobbs Cross Golf Centre",
        "town":  "Epping",
        "postcode":  "CM16 7NQ",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "35 + 27",
        "lat":  51.681804,
        "lng":  0.134614,
        "distanceMiles":  16.4,
        "website":  "https://www.hobbscrossgolfcentre.com/",
        "phone":  "+44 1992 561 661"
    },
    {
        "osmType":  "way",
        "osmId":  231370473,
        "name":  "Abridge Golf and Country Club",
        "town":  "Stapleford Tawney",
        "postcode":  "RM4 1ST",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.66659,
        "lng":  0.147339,
        "distanceMiles":  15.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  244589931,
        "name":  "Upchurch River Valley North Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "4,4,3,4,5,4,3,4,5,4,3,4,3,4,4,3,4,4",
        "lat":  51.370812,
        "lng":  0.635637,
        "distanceMiles":  15.2,
        "website":  "https://www.rivervalleygolf.co.uk/golf.html",
        "phone":  "+44 1634 379592"
    },
    {
        "osmType":  "way",
        "osmId":  228460387,
        "name":  "North Weald Golf Club - Par 3",
        "town":  "North Weald",
        "postcode":  "CM16 6AR",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "27",
        "lat":  51.711535,
        "lng":  0.150076,
        "distanceMiles":  18,
        "website":  "http://www.northwealdgolfclub.co.uk/",
        "phone":  "+441992524142"
    },
    {
        "osmType":  "way",
        "osmId":  183480485,
        "name":  "Ingrebourne Links Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.513613,
        "lng":  0.230958,
        "distanceMiles":  4.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  205993614,
        "name":  "Crondon Park Golf \u0026 Country Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.675416,
        "lng":  0.440505,
        "distanceMiles":  14.7,
        "website":  "http://www.crondon.com/",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  226276922,
        "name":  "Epping Golf Course",
        "town":  "Epping",
        "postcode":  "CM16 7NJ",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "68",
        "lat":  51.684696,
        "lng":  0.122741,
        "distanceMiles":  16.9,
        "website":  "https://www.eppinggolfcourse.org.uk/",
        "phone":  "+44 1992572282"
    },
    {
        "osmType":  "way",
        "osmId":  105680581,
        "name":  "Allhallows Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.470563,
        "lng":  0.651518,
        "distanceMiles":  14.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  92613346,
        "name":  "Hylands Golf Complex \u0026 Academy",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.700401,
        "lng":  0.426785,
        "distanceMiles":  16.2,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  93365211,
        "name":  "Sittingbourne \u0026 Milton Regis Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.337981,
        "lng":  0.66818,
        "distanceMiles":  17.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  94420394,
        "name":  "Tudor Park Country Club",
        "town":  "Bearsted",
        "postcode":  "ME14 4NQ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.262035,
        "lng":  0.589155,
        "distanceMiles":  18.6,
        "website":  "https://www.marriott.co.uk/hotels/hotel-information/golf-courses/tdmgs-tudor-park-a-marriott-hotel-and-country-club/",
        "phone":  "+44 1622 734 334"
    },
    {
        "osmType":  "way",
        "osmId":  92136781,
        "name":  "Snodhurst Bottom Pitch \u0026 Putt",
        "town":  "",
        "postcode":  "",
        "holesTag":  "pitch_and_putt",
        "holesCount":  9,
        "par":  "",
        "lat":  51.361117,
        "lng":  0.523397,
        "distanceMiles":  11.6,
        "website":  "",
        "phone":  "+44 1634 843167"
    },
    {
        "osmType":  "way",
        "osmId":  48058296,
        "name":  "Loughton Golf Club",
        "town":  "Loughton",
        "postcode":  "IG10 2BF",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "34",
        "lat":  51.662659,
        "lng":  0.075004,
        "distanceMiles":  16.8,
        "website":  "https://www.loughtongolfclub.com/",
        "phone":  "+44 20 8502 2923"
    },
    {
        "osmType":  "way",
        "osmId":  83499726,
        "name":  "Tonbridge Golf Centre",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.200037,
        "lng":  0.287648,
        "distanceMiles":  19.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  88488836,
        "name":  "Bearsted Golf Club",
        "town":  "Maidstone",
        "postcode":  "ME14 4PQ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.279507,
        "lng":  0.57355,
        "distanceMiles":  17.3,
        "website":  "https://www.bearstedgolfclub.co.uk/",
        "phone":  "+44 1622 738 198"
    },
    {
        "osmType":  "way",
        "osmId":  100876758,
        "name":  "Castle Point Golf Course",
        "town":  "Canvey Island",
        "postcode":  "SS8 9FG",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.534569,
        "lng":  0.580159,
        "distanceMiles":  11.7,
        "website":  "https://www.glendalegolf.co.uk/Castle-point-golf-course",
        "phone":  "+44 1268 511149"
    },
    {
        "osmType":  "way",
        "osmId":  101963760,
        "name":  "Cranfield Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.576944,
        "lng":  0.148792,
        "distanceMiles":  10.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  103426735,
        "name":  "The Rayleigh Club",
        "town":  "",
        "postcode":  "SS6 9QS",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.609677,
        "lng":  0.615257,
        "distanceMiles":  15.5,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  100791079,
        "name":  "Garon Park Golf Complex",
        "town":  "Southend-on-Sea",
        "postcode":  "SS2 4FA",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "35 + 35 + 35",
        "lat":  51.553164,
        "lng":  0.742203,
        "distanceMiles":  18.7,
        "website":  "https://www.garonparkgolf.co.uk/",
        "phone":  "+44 1702 601 701"
    },
    {
        "osmType":  "way",
        "osmId":  94440441,
        "name":  "Kings Hill Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.26499,
        "lng":  0.401145,
        "distanceMiles":  14.9,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  94530214,
        "name":  "Saint Cleres Hall Golf Club",
        "town":  "Stanford Le Hope",
        "postcode":  "",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.50759,
        "lng":  0.410656,
        "distanceMiles":  4.3,
        "website":  "http://stclereshallgolfclub.weebly.com/",
        "phone":  "+44 1375 673007;+44 1375 361565"
    },
    {
        "osmType":  "way",
        "osmId":  94530219,
        "name":  "Orsett Golf Club",
        "town":  "Orsett",
        "postcode":  "RM16 3DR",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.498807,
        "lng":  0.390301,
        "distanceMiles":  3.2,
        "website":  "https://www.orsettgolfclub.co.uk/",
        "phone":  "+44 1375 891352"
    },
    {
        "osmType":  "relation",
        "osmId":  3902075,
        "name":  "Gravesend Golf Centre",
        "town":  "Gravesend",
        "postcode":  "DA12 4LG",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "27",
        "lat":  51.422422,
        "lng":  0.405488,
        "distanceMiles":  5,
        "website":  "https://www.gravesendgolfcentre.com/",
        "phone":  "+44 1474 335 002"
    },
    {
        "osmType":  "relation",
        "osmId":  3908574,
        "name":  "Brentwood Golf Centre at Hartswood",
        "town":  "Brentwood",
        "postcode":  "CM14 5AE",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "70",
        "lat":  51.607225,
        "lng":  0.325331,
        "distanceMiles":  9.1,
        "website":  "https://www.brentwood.gov.uk/index.php?cid=431",
        "phone":  "+44 1277 312500"
    },
    {
        "osmType":  "relation",
        "osmId":  3910795,
        "name":  "Stapleford Abbotts Golf Course",
        "town":  "Stapleford Abbotts",
        "postcode":  "RM4 1JU",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "72 + 27",
        "lat":  51.636229,
        "lng":  0.205635,
        "distanceMiles":  12.2,
        "website":  "https://staplefordabbottsgolf.co.uk/",
        "phone":  "+44 1708 381 108"
    },
    {
        "osmType":  "relation",
        "osmId":  3883401,
        "name":  "West Malling Golf Course",
        "town":  "Addington",
        "postcode":  "ME19 5AR",
        "holesTag":  "36_hole",
        "holesCount":  36,
        "par":  "70 + 70",
        "lat":  51.303555,
        "lng":  0.369317,
        "distanceMiles":  12,
        "website":  "https://www.westmallinggolf.com/",
        "phone":  "+44 1732 844785"
    },
    {
        "osmType":  "relation",
        "osmId":  3369224,
        "name":  "Gillingham Golf Club",
        "town":  "Gillingham",
        "postcode":  "ME7 2AP",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "68",
        "lat":  51.375974,
        "lng":  0.56743,
        "distanceMiles":  12.5,
        "website":  "https://www.gillinghamgolfclub.co.uk/",
        "phone":  "+44 1634 853017"
    },
    {
        "osmType":  "relation",
        "osmId":  3393960,
        "name":  "Poult Wood Golf Course - 18 Hole",
        "town":  "Tonbridge",
        "postcode":  "TN11 9QR",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "68 + 28",
        "lat":  51.223019,
        "lng":  0.302897,
        "distanceMiles":  17.5,
        "website":  "https://www.tmactive.co.uk/locations/poult-wood",
        "phone":  "+44 1732 364039"
    },
    {
        "osmType":  "relation",
        "osmId":  3883387,
        "name":  "Wanstead Golf Club",
        "town":  "London",
        "postcode":  "E11 2LW",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "69",
        "lat":  51.571007,
        "lng":  0.032713,
        "distanceMiles":  14.2,
        "website":  "http://www.wansteadgolf.org.uk/",
        "phone":  "+44 20 8989 9876;+44 20 8989 3938"
    },
    {
        "osmType":  "relation",
        "osmId":  16053213,
        "name":  "Poult Wood Golf Course - 9 Hole",
        "town":  "Tonbridge",
        "postcode":  "TN11 9QR",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.223935,
        "lng":  0.296122,
        "distanceMiles":  17.4,
        "website":  "https://www.tmactive.co.uk/locations/poult-wood",
        "phone":  ""
    },
    {
        "osmType":  "relation",
        "osmId":  18079483,
        "name":  "Upminster Golf and Bowling Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.565202,
        "lng":  0.2504,
        "distanceMiles":  7,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "relation",
        "osmId":  19543943,
        "name":  "High Elms Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.347195,
        "lng":  0.072221,
        "distanceMiles":  14,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "relation",
        "osmId":  14104649,
        "name":  "Ilford Golf Club",
        "town":  "Ilford",
        "postcode":  "IG1 3FL",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.561785,
        "lng":  0.056936,
        "distanceMiles":  13,
        "website":  "https://www.ilfordgolfclub.co.uk/",
        "phone":  ""
    },
    {
        "osmType":  "relation",
        "osmId":  4034056,
        "name":  "Addington Court Golf Club",
        "town":  "Croydon",
        "postcode":  "CR0 9AA",
        "holesTag":  "45_hole",
        "holesCount":  45,
        "par":  "68 + 68 + 31",
        "lat":  51.345989,
        "lng":  -0.028839,
        "distanceMiles":  17.7,
        "website":  "https://www.addingtoncourt-golfclub.co.uk/",
        "phone":  "+44 20 8657 0281"
    },
    {
        "osmType":  "relation",
        "osmId":  8042122,
        "name":  "Park Wood Golf Club",
        "town":  "Tatsfield",
        "postcode":  "TN16 2EG",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.289528,
        "lng":  0.031512,
        "distanceMiles":  18,
        "website":  "https://www.parkwoodgolf.co.uk/",
        "phone":  "+44 1959 577177;+44 1959 577744"
    },
    {
        "osmType":  "relation",
        "osmId":  9356589,
        "name":  "Langley Park Golf Course",
        "town":  "Beckenham",
        "postcode":  "BR3 6SZ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.384922,
        "lng":  -0.010105,
        "distanceMiles":  15.7,
        "website":  "",
        "phone":  "+44 20 8658 6849"
    },
    {
        "osmType":  "relation",
        "osmId":  2866482,
        "name":  "Darenth Valley Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.326877,
        "lng":  0.183612,
        "distanceMiles":  11.9,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  265879314,
        "name":  "Falconwood Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.347465,
        "lng":  -0.027631,
        "distanceMiles":  17.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  293353027,
        "name":  "Sparrows Den Pitch \u0026 Putt",
        "town":  "West Wickham",
        "postcode":  "BR4 9BB",
        "holesTag":  "pitch_and_putt",
        "holesCount":  9,
        "par":  "",
        "lat":  51.368906,
        "lng":  -0.010078,
        "distanceMiles":  16.2,
        "website":  "",
        "phone":  "+44 20 8777 5010"
    },
    {
        "osmType":  "way",
        "osmId":  350806648,
        "name":  "Mardyke Valley Golf Club",
        "town":  "",
        "postcode":  "RM15 6RR",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "70",
        "lat":  51.503425,
        "lng":  0.303971,
        "distanceMiles":  2.1,
        "website":  "https://www.mardykevalley.co.uk/",
        "phone":  "+44 1708 855011"
    },
    {
        "osmType":  "way",
        "osmId":  262444890,
        "name":  "Langdon Hills Golf and Country Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "35 + 36 + 37",
        "lat":  51.544871,
        "lng":  0.395428,
        "distanceMiles":  5.7,
        "website":  "https://www.golflangdon.co.uk/",
        "phone":  "+44 1268 548444"
    },
    {
        "osmType":  "way",
        "osmId":  244589932,
        "name":  "Upchurch River Valley South Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "5,3,4,3,5,4,4,5,3",
        "lat":  51.363295,
        "lng":  0.634286,
        "distanceMiles":  15.4,
        "website":  "https://www.rivervalleygolf.co.uk/golf.html",
        "phone":  "+44 1634 379592"
    },
    {
        "osmType":  "way",
        "osmId":  244589933,
        "name":  "Upchurch River Valley West Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "4,4,4,4,4,3,3,3,4",
        "lat":  51.36767,
        "lng":  0.634844,
        "distanceMiles":  15.3,
        "website":  "https://www.rivervalleygolf.co.uk/golf.html",
        "phone":  "+44 1634 379592"
    },
    {
        "osmType":  "way",
        "osmId":  253235071,
        "name":  "High Beech Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.669151,
        "lng":  0.03229,
        "distanceMiles":  18.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  967963258,
        "name":  "Knole Park Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "",
        "lat":  51.26762,
        "lng":  0.210688,
        "distanceMiles":  15.2,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  1437244489,
        "name":  "The Addington Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.364113,
        "lng":  -0.038909,
        "distanceMiles":  17.5,
        "website":  "https://addingtongolf.com/",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  1493514491,
        "name":  "Stock Brook Country Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.650612,
        "lng":  0.424024,
        "distanceMiles":  12.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  914183132,
        "name":  "The Burstead Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.608932,
        "lng":  0.403989,
        "distanceMiles":  9.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  400792537,
        "name":  "Woodford Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.616555,
        "lng":  0.017146,
        "distanceMiles":  16.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  485708432,
        "name":  "South Norwood Pitch and Putt",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.397139,
        "lng":  -0.059975,
        "distanceMiles":  17.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  909368323,
        "name":  "Basildon Golf Course",
        "town":  "Basildon",
        "postcode":  "SS16 5JP",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.560473,
        "lng":  0.470162,
        "distanceMiles":  8.6,
        "website":  "https://basildongolfcourse.com/",
        "phone":  "+44 1268 533532"
    },
    {
        "osmType":  "way",
        "osmId":  34286692,
        "name":  "Boyce Hill Golf Course",
        "town":  "Benfleet",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.553386,
        "lng":  0.569662,
        "distanceMiles":  11.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5054370,
        "name":  "Wrotham Heath Golf Club",
        "town":  "Sevenoaks",
        "postcode":  "TN15 8QZ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.293179,
        "lng":  0.343235,
        "distanceMiles":  12.6,
        "website":  "https://www.wrothamheathgolfclub.co.uk/",
        "phone":  "+44 1732 884 800"
    },
    {
        "osmType":  "way",
        "osmId":  5059666,
        "name":  "Chelsfield Lakes Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.348814,
        "lng":  0.123843,
        "distanceMiles":  12.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5059692,
        "name":  "Farleigh Golf Club",
        "town":  "Warlingham",
        "postcode":  "CR6 9PE",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "36 + 36 + 36",
        "lat":  51.331405,
        "lng":  -0.033287,
        "distanceMiles":  18.4,
        "website":  "https://www.farleighfox.co.uk/",
        "phone":  "+44 1883 62 77 11"
    },
    {
        "osmType":  "way",
        "osmId":  5052497,
        "name":  "Redlibbets Golf Club",
        "town":  "",
        "postcode":  "TN15 7HT",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.374413,
        "lng":  0.29415,
        "distanceMiles":  7.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5051893,
        "name":  "Pedham Place Golf Centre",
        "town":  "Swanley",
        "postcode":  "BR8 8PP",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "72 + 27",
        "lat":  51.379899,
        "lng":  0.201096,
        "distanceMiles":  8.5,
        "website":  "https://www.ppgc.co.uk/",
        "phone":  "+44 1322 86 7000"
    },
    {
        "osmType":  "way",
        "osmId":  5051910,
        "name":  "Princes Park Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "27",
        "lat":  51.434899,
        "lng":  0.230289,
        "distanceMiles":  4.9,
        "website":  "http://www.dartfordfconline.com/site/?q=pages/princes-park-golf-course",
        "phone":  "+44 1322 299991"
    },
    {
        "osmType":  "way",
        "osmId":  5051929,
        "name":  "Orpington Golf Centre",
        "town":  "Orpington",
        "postcode":  "BR5 3HY",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.405432,
        "lng":  0.131108,
        "distanceMiles":  9.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5104278,
        "name":  "Shortlands Golf Club",
        "town":  "Bromley",
        "postcode":  "BR2 0BP",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "34",
        "lat":  51.41092,
        "lng":  0.000306,
        "distanceMiles":  14.7,
        "website":  "https://www.shortlandsgolfclub.com/",
        "phone":  "+44 20 8466 9155"
    },
    {
        "osmType":  "way",
        "osmId":  5104288,
        "name":  "Croham Hurst Golf Course",
        "town":  "South Croydon",
        "postcode":  "CR2 7HJ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.351564,
        "lng":  -0.074045,
        "distanceMiles":  19.2,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5107760,
        "name":  "West Kent Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.331958,
        "lng":  0.045172,
        "distanceMiles":  15.6,
        "website":  "https://www.wkgc.co.uk/",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5096880,
        "name":  "Royal Blackheath Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.443581,
        "lng":  0.05789,
        "distanceMiles":  11.7,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5069119,
        "name":  "Nizels",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.231595,
        "lng":  0.208292,
        "distanceMiles":  17.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5081162,
        "name":  "Westerham Golf Club",
        "town":  "Westerham",
        "postcode":  "TN16 1QN",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.267041999999996,
        "lng":  0.095994,
        "distanceMiles":  17.5,
        "website":  "https://www.westerhamgc.co.uk/",
        "phone":  "+44 1959 567 100"
    },
    {
        "osmType":  "way",
        "osmId":  5096627,
        "name":  "Shooters Hill Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "69",
        "lat":  51.471235,
        "lng":  0.077867,
        "distanceMiles":  10.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5051809,
        "name":  "Lullingstone Park Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.359608,
        "lng":  0.175576,
        "distanceMiles":  10.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  4289483,
        "name":  "Risebridge Golf Centre",
        "town":  "Romford",
        "postcode":  "RM1 4DG",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.598301,
        "lng":  0.193498,
        "distanceMiles":  10.2,
        "website":  "https://www.risebridgegolf.com/",
        "phone":  "+44 1708 741429"
    },
    {
        "osmType":  "way",
        "osmId":  4289772,
        "name":  "Romford Golf Club",
        "town":  "Romford",
        "postcode":  "RM2 5QB",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.59125,
        "lng":  0.200511,
        "distanceMiles":  9.6,
        "website":  "https://www.romfordgolfclub.com/",
        "phone":  "+44 1708 749393;+44 1708 740986"
    },
    {
        "osmType":  "way",
        "osmId":  4402555,
        "name":  "Brimsdown Sports \u0026 Social Club Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.657004,
        "lng":  -0.037145,
        "distanceMiles":  20,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  4282738,
        "name":  "Stapleford Abbotts - Priors Golf Course",
        "town":  "Stapleford Abbotts",
        "postcode":  "RM4 1JU",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "70",
        "lat":  51.63231,
        "lng":  0.217254,
        "distanceMiles":  11.8,
        "website":  "https://staplefordabbottsgolf.co.uk/",
        "phone":  "+44 1277 373 344"
    },
    {
        "osmType":  "way",
        "osmId":  4078565,
        "name":  "Lee Valley Golf Course",
        "town":  "London",
        "postcode":  "N9 0AR",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "67",
        "lat":  51.632447,
        "lng":  -0.034152,
        "distanceMiles":  18.9,
        "website":  "https://www.visitleevalley.org.uk/en/content/cms/outdoors/golf/golf-courses-in-london/",
        "phone":  "+44 20 8803 3611"
    },
    {
        "osmType":  "way",
        "osmId":  4269507,
        "name":  "Chigwell Golf Club",
        "town":  "Chigwell",
        "postcode":  "IG7 5BH",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.613302,
        "lng":  0.074684,
        "distanceMiles":  14.4,
        "website":  "https://www.chigwellgolfclub.co.uk/",
        "phone":  "+44 20 8500 2059;+44 20 8500 2384"
    },
    {
        "osmType":  "way",
        "osmId":  4276377,
        "name":  "Woolston Manor Golf \u0026 Country Club",
        "town":  "Chigwell",
        "postcode":  "IG7 6BX",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.640942,
        "lng":  0.093699,
        "distanceMiles":  15.2,
        "website":  "https://www.woolstonmanor.co.uk/",
        "phone":  "+44 20 8500 2549"
    },
    {
        "osmType":  "way",
        "osmId":  4974222,
        "name":  "Mid Kent Golf Club",
        "town":  "Gravesend",
        "postcode":  "DA11 7RB",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "70",
        "lat":  51.422099,
        "lng":  0.365254,
        "distanceMiles":  4.1,
        "website":  "https://mkgc.co.uk/",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5013935,
        "name":  "Wildernesse Club",
        "town":  "Sevenoaks",
        "postcode":  "TN15 0JE",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.280408,
        "lng":  0.226191,
        "distanceMiles":  14.1,
        "website":  "https://www.wildernesse.co.uk/",
        "phone":  "+44 1732 761199"
    },
    {
        "osmType":  "way",
        "osmId":  5020251,
        "name":  "Addington Palace Golf Club",
        "town":  "Croydon",
        "postcode":  "CR0 5BB",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.361645,
        "lng":  -0.042992,
        "distanceMiles":  17.7,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  4931195,
        "name":  "Sidcup Golf Club",
        "town":  "Sidcup",
        "postcode":  "DA15 9AW",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "34",
        "lat":  51.440755,
        "lng":  0.10963,
        "distanceMiles":  9.6,
        "website":  "https://www.sidcupgolfclub.co.uk/",
        "phone":  "+44 20 8300 2150"
    },
    {
        "osmType":  "way",
        "osmId":  4698645,
        "name":  "Weald Park Hotel Golf and Country Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "",
        "lat":  51.637794,
        "lng":  0.245602,
        "distanceMiles":  11.7,
        "website":  "https://www.brentwoodgolfclub.co.uk/",
        "phone":  "+441277375101"
    },
    {
        "osmType":  "way",
        "osmId":  4928105,
        "name":  "London Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.345462,
        "lng":  0.286552,
        "distanceMiles":  9.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  4930823,
        "name":  "Sundridge Park Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.417406,
        "lng":  0.034803,
        "distanceMiles":  13.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  23725066,
        "name":  "Rochester and Cobham Park Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.394762,
        "lng":  0.428917,
        "distanceMiles":  7.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  25123028,
        "name":  "Maylands Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.612096,
        "lng":  0.248821,
        "distanceMiles":  10,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  25925045,
        "name":  "Hainault Golf Club",
        "town":  "Chigwell",
        "postcode":  "IG7 4QW",
        "holesTag":  "36_hole",
        "holesCount":  36,
        "par":  "70 + 72",
        "lat":  51.615062,
        "lng":  0.140478,
        "distanceMiles":  12.5,
        "website":  "https://www.hainaultgolfclub.co.uk/",
        "phone":  "+44 20 8500 2131"
    },
    {
        "osmType":  "way",
        "osmId":  23618344,
        "name":  "South Essex Golf Centre",
        "town":  "Brentwood",
        "postcode":  "CM13 3LW",
        "holesTag":  "27_hole",
        "holesCount":  27,
        "par":  "36 + 36 + 35",
        "lat":  51.587385,
        "lng":  0.366777,
        "distanceMiles":  7.9,
        "website":  "https://www.southessexgolf.co.uk/index.php",
        "phone":  "+44 1277 811 289"
    },
    {
        "osmType":  "way",
        "osmId":  23307354,
        "name":  "Blakes Golf Course",
        "town":  "North Weald",
        "postcode":  "CM16 6RZ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.720047,
        "lng":  0.187341,
        "distanceMiles":  17.9,
        "website":  "https://www.blakesgolfclub.com/",
        "phone":  "+44 1992 525151"
    },
    {
        "osmType":  "way",
        "osmId":  23454278,
        "name":  "Cranham Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.555764,
        "lng":  0.282267,
        "distanceMiles":  5.9,
        "website":  "https://www.cranhamgolfcourse.co.uk/",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  23608856,
        "name":  "Top Meadow",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.541154,
        "lng":  0.312411,
        "distanceMiles":  4.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  28671616,
        "name":  "Fawkham Valley Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.385299,
        "lng":  0.294437,
        "distanceMiles":  6.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  29109672,
        "name":  "Rochford Hall Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.578955,
        "lng":  0.697643,
        "distanceMiles":  17.5,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  32798441,
        "name":  "Chelmsford Golf Course",
        "town":  "Chelmsford",
        "postcode":  "CM2 9AP",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.714425,
        "lng":  0.455348,
        "distanceMiles":  17.4,
        "website":  "https://www.chelmsfordgc.co.uk/",
        "phone":  "+44 1245 256483"
    },
    {
        "osmType":  "way",
        "osmId":  28303055,
        "name":  "Cobtree Manor Park Golf Club",
        "town":  "",
        "postcode":  "ME14 3AZ",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.303267,
        "lng":  0.506975,
        "distanceMiles":  14.2,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  25938354,
        "name":  "Dunton Hills",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.570049,
        "lng":  0.370668,
        "distanceMiles":  6.8,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  26576485,
        "name":  "Aquarius Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.454989,
        "lng":  -0.052964,
        "distanceMiles":  16.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  28237051,
        "name":  "Dulwich and Sydenham Hill Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.438935,
        "lng":  -0.073853,
        "distanceMiles":  17.4,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  23198673,
        "name":  "West Essex Golf Club",
        "town":  "London",
        "postcode":  "E4 7QL",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.65076,
        "lng":  0.013404,
        "distanceMiles":  18.1,
        "website":  "https://www.westessexgolfclub.co.uk/",
        "phone":  "+44 20 8529 7558;+44 20 8529 4367"
    },
    {
        "osmType":  "way",
        "osmId":  7850293,
        "name":  "Bentley Golf Course",
        "town":  "Brentwood",
        "postcode":  "CM15 9SS",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "72",
        "lat":  51.652155,
        "lng":  0.271707,
        "distanceMiles":  12.4,
        "website":  "https://www.bentleygolfclub.com/",
        "phone":  "+44 1277 373179"
    },
    {
        "osmType":  "way",
        "osmId":  7975880,
        "name":  "Chislehurst Golf Course",
        "town":  "Chislehurst",
        "postcode":  "BR7 5HJ",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "66",
        "lat":  51.413725,
        "lng":  0.062926,
        "distanceMiles":  12.1,
        "website":  "https://www.chislehurstgolfclub.co.uk/",
        "phone":  "+44 20 8467 2782"
    },
    {
        "osmType":  "way",
        "osmId":  9940299,
        "name":  "Bromley Golf Centre",
        "town":  "Keston",
        "postcode":  "BR2 8JF",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "35",
        "lat":  51.384127,
        "lng":  0.049376,
        "distanceMiles":  13.4,
        "website":  "https://www.mytimeactive.co.uk/golf/centres/bromley/",
        "phone":  "+44 20 8462 7014"
    },
    {
        "osmType":  "way",
        "osmId":  5214805,
        "name":  "Bexleyheath Golf Club",
        "town":  "Bexleyheath",
        "postcode":  "DA6 8JS",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.4503,
        "lng":  0.132244,
        "distanceMiles":  8.5,
        "website":  "http://bexleyheath-golf.com/",
        "phone":  "+44 20 8303 6951"
    },
    {
        "osmType":  "way",
        "osmId":  5107818,
        "name":  "Cherry Lodge Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.310252,
        "lng":  0.058031,
        "distanceMiles":  16.2,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5133605,
        "name":  "Dartford Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.435069,
        "lng":  0.20045,
        "distanceMiles":  6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  5154232,
        "name":  "Barnehurst Golf Course",
        "town":  "Barnehurst",
        "postcode":  "",
        "holesTag":  "9_hole",
        "holesCount":  9,
        "par":  "34",
        "lat":  51.460138,
        "lng":  0.172763,
        "distanceMiles":  6.6,
        "website":  "https://www.mytimeactive.co.uk/golf/centres/barnehurst/default.aspx",
        "phone":  "+44 1322 523746"
    },
    {
        "osmType":  "way",
        "osmId":  19786966,
        "name":  "Hilden Golf Centre",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.212159,
        "lng":  0.230201,
        "distanceMiles":  18.6,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  21130465,
        "name":  "Theydon Bois Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.67984,
        "lng":  0.093726,
        "distanceMiles":  17.3,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  23198505,
        "name":  "Chingford Golf Course",
        "town":  "London",
        "postcode":  "E4 6AN",
        "holesTag":  "18_hole",
        "holesCount":  18,
        "par":  "71",
        "lat":  51.638038,
        "lng":  0.007483,
        "distanceMiles":  17.7,
        "website":  "https://www.chingfordgolfclub.org.uk/",
        "phone":  "+44 20 8529 5708"
    },
    {
        "osmType":  "way",
        "osmId":  11403148,
        "name":  "Shirley Park Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.370867,
        "lng":  -0.059665,
        "distanceMiles":  18.1,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  10374680,
        "name":  "Eltham Warren Golf Club",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.455163,
        "lng":  0.0716,
        "distanceMiles":  11,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  10712095,
        "name":  "Championship Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.341938,
        "lng":  -0.029739,
        "distanceMiles":  17.9,
        "website":  "",
        "phone":  ""
    },
    {
        "osmType":  "way",
        "osmId":  10934741,
        "name":  "Birchwood Park Golf Course",
        "town":  "",
        "postcode":  "",
        "holesTag":  "",
        "holesCount":  18,
        "par":  "",
        "lat":  51.414339,
        "lng":  0.160313,
        "distanceMiles":  8.2,
        "website":  "",
        "phone":  ""
    }
];
